// src/constants/categories.js

export const CATEGORIES = [
  // Electronics & Tech
  "Electronics",
  "Computers & Laptops",
  "Laptops",
  "Desktops",
  "Tablets",
  "Computer Accessories",
  "Monitors",
  "Keyboards",
  "Mice",
  "Printers & Scanners",
  "Networking Equipment",
  "Routers",
  "Modems",
  "External Storage",
  "USB Drives",
  "Memory Cards",
  "Computer Components",
  "Processors",
  "Graphics Cards",
  "Motherboards",
  "Power Supplies",
  "Computer Cases",
  "Cooling Systems",

  // Phones & Communication
  "Mobile Phones",
  "Smartphones",
  "Cell Phone Accessories",
  "Chargers",
  "Phone Cases",
  "Screen Protectors",
  "Wireless Chargers",
  "Power Banks",
  "Bluetooth Headsets",
  "Landline Phones",

  // Audio & Video
  "Audio & Headphones",
  "Headphones",
  "Earbuds",
  "Speakers",
  "Soundbars",
  "Car Audio",
  "Home Theater Systems",
  "Televisions",
  "Projectors",
  "Media Players",
  "Streaming Devices",

  // Cameras & Photography
  "Cameras",
  "DSLR Cameras",
  "Mirrorless Cameras",
  "Action Cameras",
  "Lenses",
  "Camera Accessories",
  "Tripods",
  "Camera Bags",
  "Flashes",
  "Binoculars",

  // Smart Home & IoT
  "Smart Home",
  "Smart Thermostats",
  "Smart Lighting",
  "Smart Locks",
  "Smart Plugs",
  "Security Cameras",
  "Video Doorbells",
  "Smart Speakers",
  "Home Automation",

  // Fashion
  "Men's Clothing",
  "Shirts & Tops",
  "T-Shirts",
  "Polos",
  "Dress Shirts",
  "Sweaters",
  "Hoodies",
  "Jackets",
  "Coats",
  "Jeans",
  "Trousers",
  "Shorts",
  "Suits & Blazers",
  "Sleepwear",
  "Underwear",
  "Socks",

  "Women's Clothing",
  "Dresses",
  "Tops & Blouses",
  "T-Shirts",
  "Sweaters",
  "Cardigans",
  "Jackets",
  "Coats",
  "Jeans",
  "Trousers",
  "Skirts",
  "Shorts",
  "Suits & Blazers",
  "Sleepwear",
  "Lingerie",
  "Swimwear",

  "Kids' Clothing",
  "Boys' Clothing",
  "Girls' Clothing",
  "Baby Clothing",
  "Infant Wear",
  "Children's Accessories",

  "Shoes",
  "Men's Shoes",
  "Women's Shoes",
  "Kids' Shoes",
  "Athletic Shoes",
  "Boots",
  "Sandals",
  "Slippers",
  "Formal Shoes",

  "Accessories",
  "Watches",
  "Jewelry",
  "Necklaces",
  "Earrings",
  "Rings",
  "Bracelets",
  "Belts",
  "Hats",
  "Scarves",
  "Handbags",
  "Backpacks",
  "Wallets",

  // Home & Kitchen
  "Furniture",
  "Living Room Furniture",
  "Sofas",
  "Sectionals",
  "Coffee Tables",
  "End Tables",
  "TV Stands",
  "Bedroom Furniture",
  "Beds",
  "Mattresses",
  "Nightstands",
  "Dressers",
  "Wardrobes",
  "Dining Room Furniture",
  "Dining Tables",
  "Dining Chairs",
  "Benches",
  "Home Office Furniture",
  "Desks",
  "Office Chairs",
  "Bookcases",

  "Kitchen & Dining",
  "Cookware",
  "Pots & Pans",
  "Bakeware",
  "Cutlery",
  "Knife Sets",
  "Dinnerware",
  "Glassware",
  "Flatware",
  "Storage Containers",
  "Food Storage",
  "Small Appliances",
  "Blenders",
  "Mixers",
  "Coffee Makers",
  "Toasters",
  "Microwaves",
  "Refrigerators",
  "Dishwashers",
  "Ovens",

  "Home Decor",
  "Wall Art",
  "Mirrors",
  "Clocks",
  "Lighting",
  "Lamps",
  "Chandeliers",
  "Rugs",
  "Curtains",
  "Throw Pillows",
  "Vases",
  "Candles",

  // Books, Movies & Music
  "Books",
  "Fiction",
  "Non-Fiction",
  "Science Fiction",
  "Fantasy",
  "Romance",
  "Mystery & Thriller",
  "Historical Fiction",
  "Biographies",
  "Memoirs",
  "Self-Help",
  "Cookbooks",
  "Textbooks",
  "E-Books",
  "Audiobooks",

  "Movies & TV",
  "DVDs",
  "Blu-ray Discs",
  "Digital Movies",
  "TV Series",
  "Documentaries",

  "Music",
  "CDs",
  "Vinyl Records",
  "Digital Music",
  "Musical Instruments",
  "Guitars",
  "Pianos",
  "Drums",
  "Violins",
  "Synthesizers",
  "Sheet Music",

  // Toys & Games
  "Toys & Games",
  "Action Figures",
  "Dolls",
  "Building Sets",
  "LEGO",
  "Puzzles",
  "Board Games",
  "Card Games",
  "Outdoor Play",
  "Ride-On Toys",
  "Educational Toys",
  "Baby Toys",
  "Electronic Toys",

  "Video Games",
  "PlayStation Games",
  "Xbox Games",
  "Nintendo Games",
  "PC Games",
  "Gaming Consoles",
  "Gaming Accessories",
  "Virtual Reality",

  // Sports & Outdoors
  "Sports & Outdoors",
  "Exercise Equipment",
  "Weights",
  "Treadmills",
  "Ellipticals",
  "Yoga Mats",
  "Yoga Accessories",
  "Camping Gear",
  "Tents",
  "Sleeping Bags",
  "Camping Chairs",
  "Backpacks",
  "Hiking Gear",
  "Climbing Gear",
  "Fishing",
  "Hunting",
  "Team Sports",
  "Basketball",
  "Soccer",
  "Baseball",
  "Football",
  "Golf",
  "Tennis",
  "Racquet Sports",

  // Automotive
  "Automotive",
  "Car Parts",
  "Brakes",
  "Filters",
  "Batteries",
  "Wipers",
  "Tires",
  "Wheels",
  "Car Accessories",
  "Floor Mats",
  "Seat Covers",
  "Car Covers",
  "Car Audio",
  "GPS",
  "Dash Cams",
  "Motorcycle Parts",
  "Motorcycle Accessories",

  // Health & Personal Care
  "Health & Personal Care",
  "Vitamins & Supplements",
  "Protein Powders",
  "Fitness Trackers",
  "Health Monitors",
  "Blood Pressure Monitors",
  "Thermometers",
  "First Aid",
  "Bandages",
  "Medical Equipment",
  "Mobility Aids",
  "Personal Hygiene",
  "Shampoo",
  "Conditioner",
  "Body Wash",
  "Soap",
  "Deodorant",
  "Skincare",
  "Moisturizers",
  "Sunscreen",
  "Facial Cleansers",
  "Hair Care",
  "Hair Dryers",
  "Curling Irons",
  "Straighteners",
  "Makeup",
  "Foundation",
  "Lipstick",
  "Eyeshadow",
  "Mascara",

  // Grocery & Gourmet
  "Grocery & Gourmet",
  "Fresh Produce",
  "Fruits",
  "Vegetables",
  "Meat & Seafood",
  "Poultry",
  "Beef",
  "Pork",
  "Seafood",
  "Dairy & Eggs",
  "Cheese",
  "Butter",
  "Milk",
  "Eggs",
  "Bakery",
  "Bread",
  "Pastries",
  "Cakes",
  "Cookies",
  "Pantry Staples",
  "Rice",
  "Pasta",
  "Canned Goods",
  "Spices",
  "Oil",
  "Beverages",
  "Coffee",
  "Tea",
  "Juice",
  "Soda",
  "Water",
  "Snacks",
  "Chips",
  "Crackers",
  "Candy",
  "Chocolate",
  "Frozen Foods",
  "Ice Cream",
  "Frozen Vegetables",

  // Office & School Supplies
  "Office Supplies",
  "Paper",
  "Pens & Pencils",
  "Notebooks",
  "Binders",
  "Folders",
  "Staplers",
  "Desk Accessories",
  "Whiteboards",
  "Calendars",
  "Planners",
  "School Supplies",
  "Backpacks",
  "Art Supplies",
  "Crayons",
  "Markers",
  "Paint",

  // Home Improvement & Tools
  "Tools & Home Improvement",
  "Power Tools",
  "Drills",
  "Saws",
  "Grinders",
  "Sanders",
  "Hand Tools",
  "Wrenches",
  "Screwdrivers",
  "Hammers",
  "Plungers",
  "Electrical",
  "Lighting",
  "Wiring",
  "Switches",
  "Plumbing",
  "Pipes",
  "Faucets",
  "Hardware",
  "Nails",
  "Screws",
  "Brackets",
  "Garden Tools",
  "Lawn Mowers",
  "Trimmers",
  "Hoses",

  // Garden & Outdoor Living
  "Garden & Outdoor",
  "Plants",
  "Seeds",
  "Soil",
  "Fertilizers",
  "Pots & Planters",
  "Patio Furniture",
  "Outdoor Decor",
  "Grills",
  "Fire Pits",
  "Gazebos",

  // Pet Supplies
  "Pet Supplies",
  "Dog Food",
  "Cat Food",
  "Bird Food",
  "Fish Food",
  "Pet Accessories",
  "Leashes",
  "Collars",
  "Pet Carriers",
  "Pet Beds",
  "Pet Toys",
  "Grooming Supplies",
  "Pet Health",
  "Pet Vitamins",

  // Arts, Crafts & Sewing
  "Arts & Crafts",
  "Sewing Machines",
  "Fabric",
  "Yarn",
  "Knitting Supplies",
  "Beads",
  "Jewelry Making",
  "Scrapbooking",
  "Craft Kits",
  "Clay",

  // Industrial & Scientific
  "Industrial",
  "Science Kits",
  "Lab Equipment",
  "Safety Gear",
  "Workwear",
  "Welding Supplies",
  "Raw Materials",

  // Baby Products
  "Baby Products",
  "Diapers",
  "Baby Food",
  "Baby Formula",
  "Baby Monitors",
  "Strollers",
  "Car Seats",
  "Playpens",
  "Baby Toys",
  "Baby Clothing",
  "Baby Furniture",

  // Other
  "Gift Cards",
  "Party Supplies",
  "Travel Accessories",
  "Luggage",
  "Passport Holders",
  "Pet Travel",
  "Maternity",
  "Sexual Wellness"
];

export default CATEGORIES;