// src/styles/homeStyles.ts
import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

// --- Colors and Constants ---
export const Colors = {
  white: "#FFFFFF",
  lightGray: "#F0F0F0",
  grayText: "#7A7A7A",
  dark: "#0A3D2B",
  darkText: "#0A3D2B",
  orange: "#0A3D2B",
  swiggyOrange: "#0A3D2B", // Retained your specific branding colors
  borderGray: "#E5E5EA",
  redAlert: "#DC2626",
  greenDark: "#0A3D2B",
  lightgreen: "#23df9eff",
  pinkPrimary: "#ff3d67",
  bluePrimary: "#4285F4",
  successGreen: "#34C759",
  sheetOverlay: "rgba(0, 0, 0, 0.6)",
  sheetBackground: "#F9F9F9",
};

// --- Stylesheet Definition ---
export const allStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "transparent" },
  container: { flex: 1, backgroundColor: "transparent" },
  
  // --- Header Styles ---
  mainHeader: {
    backgroundColor: "transparent",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    zIndex: 10,
  },
  headerTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  locationSelector: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    paddingRight: 10,
  },
  locationIconWrapper: { marginRight: 6 },
  locationTextWrapper: { flex: 1 },
  locationTitleRow: { flexDirection: "row", alignItems: "center" },
  locationTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: Colors.darkText,
    marginRight: 6,
    letterSpacing: -0.5,
  },
  locationSubtitle: {
    fontSize: 13,
    color: Colors.grayText,
    marginTop: 2,
    fontWeight: "500",
  },
  profileButton: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchBarContainer: { width: "100%" },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.white,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.02)",
  },
  searchIconGroup: { flexDirection: "row", alignItems: "center" },
  searchPlaceholder: {
    color: Colors.grayText,
    marginLeft: 10,
    fontSize: 15,
    fontWeight: "600",
  },
  searchActionsGroup: { flexDirection: "row", alignItems: "center" },
  verticalDivider: {
    width: 1,
    height: 18,
    backgroundColor: Colors.borderGray,
    marginHorizontal: 12,
  },

  // --- Modal & Address Styles ---
  modalOverlay: {
    flex: 1,
    backgroundColor: Colors.sheetOverlay,
    justifyContent: "flex-end",
  },
  bottomSheet: {
    backgroundColor: Colors.sheetBackground,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    maxHeight: height * 0.8,
    overflow: "hidden",
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.7)",
    zIndex: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomSheetHandle: {
    width: 40,
    height: 5,
    backgroundColor: "#D1D5DB",
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 16,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderGray,
  },
  sheetTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: Colors.darkText,
    letterSpacing: -0.3,
  },
  addressList: { maxHeight: height * 0.55 },
  permissionBanner: {
    backgroundColor: "#FEE2E2",
    margin: 20,
    marginBottom: 10,
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  permissionTextContainer: { flex: 1, marginRight: 12 },
  permissionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  permissionTitle: {
    color: Colors.redAlert,
    fontWeight: "700",
    fontSize: 15,
    marginLeft: 6,
  },
  permissionSubtitle: { color: "#991B1B", fontSize: 13, lineHeight: 18 },
  grantButton: {
    backgroundColor: Colors.white,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  grantButtonText: { color: Colors.redAlert, fontWeight: "bold", fontSize: 13 },
  currentLocationContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    backgroundColor: Colors.white,
    marginTop: 10,
  },
  currentLocationIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(252, 128, 25, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  currentLocationTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.swiggyOrange,
    marginBottom: 2,
  },
  sectionDivider: { height: 8, backgroundColor: "#F0F0F0", width: "100%" },
  savedAddressesHeader: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.grayText,
    letterSpacing: 0.5,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
  },
  addressItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderGray,
  },
  addressItemSelected: { backgroundColor: "rgba(52, 199, 89, 0.04)" },
  iconContainer: { width: 30, alignItems: "flex-start" },
  addressInfo: { flex: 1, paddingRight: 10 },
  addressType: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.darkText,
    marginBottom: 4,
  },
  addressString: { fontSize: 13, color: Colors.grayText, lineHeight: 18 },
  addAddressFooter: {
    padding: 16,
    paddingBottom: Platform.OS === "ios" ? 34 : 16,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.borderGray,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 10,
  },
  addAddressButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGray,
    paddingVertical: 14,
    borderRadius: 12,
  },
  addAddressButtonText: {
    color: Colors.swiggyOrange,
    fontSize: 16,
    fontWeight: "700",
    marginLeft: 8,
  },

  // --- Edit Form Styles ---
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.darkText,
    marginBottom: 8,
    marginTop: 15,
  },
  addressInput: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGray,
    borderRadius: 8,
    padding: 12,
    minHeight: 80,
    textAlignVertical: "top",
    fontSize: 15,
    color: Colors.darkText,
  },
  typeRow: { flexDirection: "row", marginTop: 5 },
  typeBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.borderGray,
    marginRight: 10,
    backgroundColor: Colors.white,
  },
  typeBadgeActive: {
    backgroundColor: "rgba(252, 128, 25, 0.1)",
    borderColor: Colors.swiggyOrange,
  },
  typeBadgeText: { fontSize: 14, color: Colors.grayText, fontWeight: "600" },
  typeBadgeTextActive: { color: Colors.swiggyOrange },
  coordText: {
    fontSize: 12,
    color: Colors.grayText,
    marginTop: 25,
    fontStyle: "italic",
  },

  // --- Page Content Styles ---
  mainContentScrollView: { flex: 1, backgroundColor: "transparent" },
  contentContainer: { paddingBottom: 60 },
  bannerWrapper: { position: "relative", marginBottom: 0, width: "100%" },
  freeShippingBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.white,
    marginHorizontal: 0,
    marginTop: 43,
    padding: 15,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: Colors.borderGray,
  },
  bannerTextContainer: { flex: 1 },
  bannerTitle: { fontSize: 16, color: Colors.dark },
  bannerTitleBold: { fontWeight: "bold", color: Colors.orange },
  bannerSubtitle: { fontSize: 12, color: Colors.grayText },
  imageBannerContainer: { width: "100%", height: 90, marginBottom: 0 },
  imageBanner: {
    width: "100%",
    height: "100%",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  categoriesSection: {
    position: "absolute",
    bottom: -40,
    left: 0,
    right: 0,
    paddingVertical: 0,
    backgroundColor: "transparent",
    zIndex: 10,
  },
  categoriesScrollContainer: { paddingHorizontal: 8, paddingBottom: 5 },
  categoryCard: {
    width: 80,
    alignItems: "center",
    marginHorizontal: 4,
    borderRadius: 8,
    paddingVertical: 5,
    height: 80,
    justifyContent: "space-between",
    zIndex: 1,
  },
  categoryImageWrapper: {
    width: 70,
    height: 70,
    borderRadius: 56,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  categoryImageSmall: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    borderRadius: 0,
  },
  categoryNameText: {
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
    color: Colors.dark,
    marginBottom: 5,
    marginTop: 9,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  sectionTitle: { fontSize: 18, fontWeight: "bold", color: Colors.dark },
  seeAllButton: { flexDirection: "row", alignItems: "center" },
  seeAllText: { color: Colors.grayText, marginRight: 2 },
  
  // --- Sections Styles ---
  horizontalSection: {
    marginTop: 10,
    backgroundColor: Colors.white,
    paddingVertical: 10,
  },
  horizontalSectionBackground: {
    marginTop: 10,
    paddingVertical: 10,
    paddingBottom: 60,
    minHeight: 50,
    width: "100%",
  },
  brandSectionBackground: {
    marginTop: 10,
    paddingVertical: 10,
    paddingBottom: 20,
    minHeight: 50,
    width: "100%",
  },
  imageBackgroundStyle: { height: 400 },
  brandImageBackgroundStyle: { height: 290 },
  contentOverlay: {},
  horizontalScrollContainer: { paddingHorizontal: 10 },
  shopHorizontalScrollContainer: {
    paddingBottom: 5,
    alignItems: "center",
    paddingHorizontal: 10,
  },
  shopCardHorizontalWrapper: {
    width: width * 0.88,
    marginRight: 10,
    marginBottom: 10,
  },
  horizontalItemContainer: {
    width: width * 1,
    marginRight: 10,
    height: width * 0.67,
  },
  gridSection: {
    marginTop: 10,
    backgroundColor: "transparent",
    paddingVertical: 10,
  },
  productGridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    paddingHorizontal: 10,
  },
  itemContainer3Col: {
    width: "100%",
    marginBottom: 15,
    marginHorizontal: 0,
    paddingHorizontal: 5,
  },
  
  // --- Loading & Error Messages ---
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  loadingText: { marginTop: 10, fontSize: 16, color: Colors.dark },
  messageContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    minHeight: 300,
  },
  messageTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: Colors.dark,
    marginBottom: 10,
  },
  messageText: {
    fontSize: 16,
    textAlign: "center",
    color: Colors.grayText,
    marginBottom: 5,
  },
  retryButton: {
    marginTop: 20,
    backgroundColor: Colors.orange,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  retryButtonText: { color: Colors.white, fontSize: 16, fontWeight: "bold" },
});