// categories.js

export const categories = {
  "Electronics": {
    "Mobile Phones & Accessories": [
      "Smartphones",
      "Feature Phones",
      "Cases & Covers",
      "Screen Protectors",
      "Power Banks & Portable Chargers",
      "Charging Cables & Adapters",
      "Wireless Chargers",
      "Car Mounts & Holders",
      "Selfie Sticks & Tripods",
      "Mobile Phone Stands",
      "Bluetooth Headsets",
      "PopSockets & Grips",
      "Replacement Batteries",
      "Camera Lens Attachments",
      "Smartwatches",
      "Fitness Trackers",
      "SIM Cards & Prepaid Plans",
      "Mobile Gaming Controllers",
      "Phone Repair Kits",
      "Water-Resistant Pouches",
      "Screen Cleaning Kits",
      "USB On-The-Go (OTG) Adapters",
      "Mobile Skins & Decals",
      "Card Holders & Wallets",
      "Ring Holders",
      "Mobile Phone Straps",
      "Mobile Phone Lanyards",
      "Mobile Phone Charms",
      "Mobile Phone Holders",
      "Mobile Phone Mounts",
      "E-book Readers",
      "Stylus Pens",
      "Phone Coolers",
      "External Microphones",
      "Portable Photo Printers",
      "Mobile Phone Cameras",
      "Mobile Phone Lenses",
      "Mobile Phone Flashes",
      "Mobile Phone Remotes",
      "Mobile Phone Filters",
      "Mobile Phone Backpacks",
      "Mobile Phone Gimbal Stabilizers",
      "Mobile Phone Drones",
      "Mobile Phone VR Headsets",
      "Mobile Phone Gamepads"
    ],
    "Laptops & Computers": [
      "Laptops",
      "Desktop PCs",
      "Gaming Laptops",
      "PC Accessories",
      "Monitors",
      "Gaming Desktops",
      "Keyboards",
      "Mice & Trackpads",
      "Webcams",
      "Printers & Scanners",
      "External Hard Drives & SSDs",
      "USB Hubs & Docks",
      "Computer Speakers",
      "Routers & Networking Equipment",
      "Computer Components (CPUs, GPUs)",
      "Laptop Bags & Sleeves",
      "Monitor Stands & Mounts",
      "PC Gaming Accessories",
      "Ergonomic Accessories",
      "Cables & Adapters",
      "Software (OS, Antivirus)",
      "Motherboards",
      "RAM (Memory)",
      "Power Supplies (PSUs)",
      "Cooling Systems (Fans, Liquid Coolers)",
      "Sound Cards",
      "Graphics Cards (GPUs)",
      "Internal Storage (HDDs, SSDs)",
      "Optical Drives",
      "PC Cases",
      "Operating Systems",
      "UPS (Uninterruptible Power Supply)",
      "KVM Switches",
      "Gaming Keypads",
      "Gaming Mouse Pads",
      "Computer Microphones",
      "PC Headsets",
      "Webcam Covers",
      "Laptop Cooling Pads",
      "Network Switches",
      "Ethernet Cables",
      "DisplayPort Cables",
      "HDMI Cables",
      "Power Strips",
      "Cable Management Solutions"
    ],
    "Audio Devices": [
      "Headphones",
      "Earbuds",
      "Bluetooth Speakers",
      "Soundbars",
      "Home Theater Systems",
      "Turntables & Vinyl",
      "Audio Receivers",
      "Microphones",
      "Car Audio",
      "Portable Audio Players",
      "Amplifiers",
      "Speaker Stands",
      "Audio Cables & Connectors",
      "DJ Equipment",
      "Recording Equipment",
      "Wired Speakers",
      "Smart Speakers",
      "Noise-Cancelling Headphones",
      "Sports Earbuds",
      "Multi-room Audio Systems",
      "Studio Monitors",
      "Headphone Amplifiers",
      "Digital-to-Analog Converters (DACs)",
      "Professional Audio Mixers",
      "PA Systems",
      "Karaoke Machines",
      "Cassette Players",
      "CD Players",
      "Home Stereo Systems",
      "Radio Receivers",
      "Podcasting Microphones",
      "Live Sound Equipment",
      "Speaker Mounts",
      "Wireless Microphones",
      "Portable PA Systems",
      "Audio Interfaces",
      "Drum Machines",
      "Synthesizers",
      "Effects Pedals",
      "MIDI Controllers",
      "Studio Headphones",
      "Mixing Consoles"
    ],
    "Cameras": [
      "DSLR Cameras",
      "Mirrorless Cameras",
      "Point & Shoot",
      "Action Cameras",
      "Drones with Cameras",
      "Camcorders",
      "Lenses",
      "Tripods & Monopods",
      "Camera Bags & Cases",
      "Memory Cards & Storage",
      "Flashes & Lighting",
      "Camera Batteries & Chargers",
      "Filters & Lens Hoods",
      "Webcams",
      "Instant Cameras",
      "Binoculars",
      "Telescopes",
      "Camera Sliders & Gimbals",
      "Studio Lighting Kits",
      "Camera Cleaning Kits",
      "Underwater Camera Housings",
      "Camera Straps",
      "Camera Drones",
      "Camera Stabilizers",
      "Camera Lenses",
      "Camera Flashes",
      "Camera Remotes",
      "Camera Filters",
      "Camera Backpacks",
      "Microphones for Cameras",
      "External Monitors",
      "Camera Cages",
      "Action Camera Mounts",
      "Lens Adapters",
      "Camera Sensors",
      "Camera Bodies",
      "Camera Kits",
      "Video Cameras",
      "Security Cameras"
    ],
    "Wearable Tech": [
      "Smartwatches",
      "Fitness Trackers",
      "Virtual Reality Headsets",
      "Smart Glasses",
      "Smart Rings",
      "Smart Jewelry",
      "Headphone Accessories",
      "Smart Clothing",
      "GPS Trackers",
      "Sleep Trackers",
      "Heart Rate Monitors",
      "Smart Backpacks",
      "Wearable Cameras",
      "Wearable Audio Devices",
      "Health and Wellness Devices",
      "Smart Scales",
      "Smartbands",
      "Smart Belts",
      "Smart Footwear",
      "Smart Gloves",
      "Wearable Displays",
      "Wearable Sensors",
      "Wearable Fitness Devices",
      "Wearable Health Monitors",
      "Wearable Payment Devices",
      "Wearable Security Devices",
      "Wearable Safety Devices",
      "Wearable Medical Devices",
      "Wearable Sleep Monitors",
      "Wearable Air Purifiers",
      "Wearable Sunscreen Applicators",
      "Smart T-shirts",
      "Smart Bras",
      "Smart Socks",
      "Smart Water Bottles",
      "Smart Headbands",
      "Smart Helmets",
      "Smart Patches"
    ],
    "Home Appliances": [
      "Televisions",
      "Refrigerators",
      "Washing Machines",
      "Air Conditioners",
      "Dishwashers",
      "Microwave Ovens",
      "Vacuum Cleaners",
      "Air Purifiers",
      "Water Purifiers",
      "Ovens",
      "Stoves & Cooktops",
      "Mixers & Blenders",
      "Coffee Makers & Espresso Machines",
      "Toasters & Toaster Ovens",
      "Electric Kettles",
      "Heaters",
      "Irons & Steamers",
      "Food Processors",
      "Rice Cookers",
      "Juicers",
      "Grills & Panini Presses",
      "Cooktops",
      "Chimneys",
      "Fans",
      "Air Coolers",
      "Food Slicers",
      "Deep Fryers",
      "Waffle Makers",
      "Ice Cream Makers",
      "Pressure Cookers",
      "Robot Vacuums",
      "Smart Ovens",
      "Smart Refrigerators",
      "Wine Coolers",
      "Garbage Disposals",
      "Trash Compactors",
      "Humidifiers",
      "Dehumidifiers",
      "Sewing Machines",
      "Smart Washing Machines",
      "Steam Cleaners",
      "Electric Toothbrushes",
      "Water Flossers"
    ],
    "Gaming": [
      "Gaming Consoles",
      "Video Games",
      "PC Gaming Accessories",
      "Gaming Chairs",
      "Gaming Desks",
      "Gaming Monitors",
      "Headsets",
      "Keyboards",
      "Mice",
      "Controllers",
      "Racing Wheels",
      "Flight Sticks",
      "Streaming Equipment",
      "Arcade Machines",
      "VR Gaming",
      "Retro Gaming Consoles",
      "Gaming Laptops",
      "Gaming PCs",
      "Gaming Mouse Pads",
      "Console Storage & Stands",
      "Gaming Headsets",
      "Gaming Keypads",
      "Gaming Joysticks",
      "Gaming Speakers",
      "Gaming Microphones",
      "Gaming Webcams",
      "Gaming Mouse Pads",
      "Gaming Headphone Stands",
      "Gaming Keyboard Stands",
      "Gaming Routers",
      "Gaming Cables",
      "Gaming Cooling Pads",
      "Gaming Peripherals",
      "Gaming Controllers",
      "Gaming Mice",
      "Gaming Keyboards",
      "Gaming Headsets",
      "Gaming Microphones"
    ]
  },
  "Fashion": {
    "Women's Fashion": {
      "Clothing": [
        "Dresses",
        "Tops, Tunics & Shirts",
        "T-Shirts",
        "Jeans & Jeggings",
        "Trousers & Tights",
        "Skirts",
        "Shorts",
        "Jumpsuits & Rompers",
        "Outerwear (Jackets, Coats, Blazers)",
        "Sweaters & Cardigans",
        "Ethnic Wear (Sarees, Kurtas, Salwar Suits)",
        "Lingerie & Innerwear",
        "Sportswear & Activewear",
        "Sleepwear & Loungewear",
        "Maternity Wear",
        "Workwear & Uniforms",
        "Swimwear",
        "Co-ords",
        "Blouses",
        "Bodycon Dresses",
        "Maxi Dresses",
        "Midi Dresses",
        "Mini Dresses",
        "Party Wear",
        "Formal Wear",
        "Casual Wear",
        "Athleisure",
        "Denim Jackets",
        "Leather Jackets",
        "Trench Coats",
        "Puffer Jackets",
        "Crop Tops",
        "Hoodies",
        "Sweatshirts",
        "Turtlenecks",
        "Tank Tops",
        "Bodysuits",
        "Leggings",
        "Palazzos",
        "Culottes",
        "Capris",
        "Pantsuits",
        "Work Dresses",
        "Sarees",
        "Kurtas",
        "Lehengas",
        "Anarkalis",
        "Salwar Suits",
        "Blouse Pieces",
        "Dupattas"
      ],
      "Footwear": [
        "Casual Shoes",
        "Sports Shoes",
        "Sandals & Flats",
        "Heels & Wedges",
        "Boots",
        "Sneakers",
        "Slippers & Clogs",
        "Loafers",
        "Espadrilles",
        "Pumps",
        "Wedges",
        "Mules",
        "Platforms",
        "Ballet Flats",
        "Stilettos",
        "Kitten Heels",
        "Ankle Boots",
        "Knee-High Boots",
        "Over-the-Knee Boots",
        "Chelsea Boots",
        "Combat Boots",
        "Hiking Boots",
        "Rain Boots",
        "Sneaker Wedges",
        "Running Shoes",
        "Training Shoes",
        "Walking Shoes",
        "Crocs",
        "Flip-Flops",
        "Slides",
        "Juttis",
        "Mojaris"
      ],
      "Bags & Wallets": [
        "Handbags",
        "Backpacks",
        "Clutches & Wallets",
        "Tote Bags",
        "Messenger & Sling Bags",
        "Duffel & Travel Bags",
        "Crossbody Bags",
        "Shoulder Bags",
        "Hobo Bags",
        "Satchels",
        "Fanny Packs",
        "Wristlets",
        "Pouches",
        "Cosmetic Bags",
        "Laptop Bags",
        "Briefcases",
        "Luggage & Suitcases",
        "Travel Organizers",
        "Jewelry Boxes"
      ],
      "Accessories": [
        "Watches",
        "Sunglasses & Eyewear",
        "Scarves & Shawls",
        "Belts",
        "Hats & Caps",
        "Gloves",
        "Hair Accessories (Bands, Clips, Pins)",
        "Keychains & Charms",
        "Umbrellas",
        "Jewelry",
        "Socks",
        "Tights & Leggings",
        "Wallets",
        "Phone Cases",
        "Earrings",
        "Necklaces",
        "Bracelets",
        "Rings",
        "Brooches",
        "Hairbands",
        "Hair Clips",
        "Hair Ties",
        "Fascinators",
        "Tiaras"
      ]
    },
    "Men's Fashion": {
      "Clothing": [
        "T-Shirts & Polos",
        "Shirts (Casual & Formal)",
        "Jeans",
        "Trousers & Chinos",
        "Shorts",
        "Outerwear (Jackets, Coats, Blazers)",
        "Sweaters & Hoodies",
        "Suits & Formal Wear",
        "Ethnic Wear (Kurtas, Sherwanis)",
        "Innerwear",
        "Socks",
        "Sportswear & Activewear",
        "Sleepwear & Loungewear",
        "Workwear & Uniforms",
        "Swimwear",
        "Co-ords",
        "Vests",
        "Blazers",
        "Tuxedos",
        "Waistcoats",
        "Jackets",
        "Coats",
        "Trench Coats",
        "Bomber Jackets",
        "Puffer Jackets",
        "Denim Jackets",
        "Leather Jackets",
        "Sweatshirts",
        "Cardigans",
        "Pullovers",
        "Trousers",
        "Chinos",
        "Cargos",
        "Joggers",
        "Lounge Pants",
        "Pajamas",
        "Boxers",
        "Briefs",
        "Trunks",
        "Vests"
      ],
      "Footwear": [
        "Casual Shoes",
        "Sports Shoes",
        "Formal Shoes",
        "Sneakers",
        "Sandals & Flip-Flops",
        "Boots",
        "Slippers & Clogs",
        "Loafers",
        "Oxfords",
        "Derbies",
        "Brogues",
        "Monk Straps",
        "Chelsea Boots",
        "Desert Boots",
        "Chukka Boots",
        "Combat Boots",
        "Hiking Boots",
        "Running Shoes",
        "Training Shoes",
        "Walking Shoes",
        "Basketball Shoes",
        "Skate Shoes",
        "Espadrilles",
        "Boat Shoes"
      ],
      "Bags & Wallets": [
        "Backpacks",
        "Wallets",
        "Messenger Bags",
        "Duffel & Travel Bags",
        "Laptop Bags",
        "Briefcases",
        "Fanny Packs",
        "Toiletry Bags",
        "Waist Bags",
        "Luggage & Suitcases",
        "Passport Holders",
        "Key Holders",
        "Money Clips"
      ],
      "Accessories": [
        "Watches",
        "Sunglasses & Eyewear",
        "Belts",
        "Hats & Caps",
        "Ties & Bow Ties",
        "Scarves & Mufflers",
        "Cufflinks",
        "Pocket Squares",
        "Gloves",
        "Jewelry",
        "Socks",
        "Wallets",
        "Phone Cases",
        "Keychains",
        "Umbrellas",
        "Bracelets",
        "Necklaces",
        "Rings",
        "Tie Clips"
      ]
    },
    "Kids & Baby": {
      "Boys' Clothing": [
        "T-Shirts & Shirts",
        "Jeans & Trousers",
        "Shorts",
        "Jackets & Sweaters",
        "Ethnic Wear",
        "Swimwear",
        "Sportswear",
        "School Uniforms",
        "Hoodies",
        "Sweatshirts",
        "Pajamas",
        "Innerwear",
        "Party Wear",
        "Formal Wear",
        "Casual Wear",
        "Athleisure",
        "Dungarees & Jumpsuits"
      ],
      "Girls' Clothing": [
        "Dresses & Jumpsuits",
        "Tops & Skirts",
        "Jeans & Tights",
        "Jackets & Sweaters",
        "Ethnic Wear",
        "Swimwear",
        "Sportswear",
        "School Uniforms",
        "Party Wear",
        "Formal Wear",
        "Casual Wear",
        "Hoodies",
        "Sweatshirts",
        "Pajamas",
        "Leggings",
        "Frocks"
      ],
      "Baby Clothing & Gear": [
        "Bodysuits & Rompers",
        "Onesies",
        "Blankets & Swaddles",
        "Infant Wear Sets",
        "Baby Shoes & Socks",
        "Feeding Accessories",
        "Diapering Needs",
        "Strollers & Prams",
        "Car Seats",
        "Baby Carriers",
        "Cribs & Cradles",
        "High Chairs",
        "Playards & Playpens",
        "Baby Monitors",
        "Baby Toys",
        "Baby Skincare",
        "Baby Grooming",
        "Baby Health",
        "Baby Feeding",
        "Baby Bathing"
      ],
      "Footwear": [
        "Shoes",
        "Sandals",
        "Slippers",
        "Sneakers",
        "Boots",
        "School Shoes",
        "Party Shoes"
      ],
      "Accessories": [
        "Hats & Caps",
        "Bags & Backpacks",
        "Hair Accessories",
        "Socks & Tights",
        "Belts & Suspenders",
        "Watches",
        "Sunglasses",
        "Jewelry",
        "Gloves",
        "Scarves",
        "Umbrellas",
        "Wallets",
        "Keychains"
      ]
    }
  },
  "Jewelry & Watches": {
    "Fine Jewelry": [
      "Gold Jewelry",
      "Diamond Jewelry",
      "Platinum Jewelry",
      "Precious Gemstone Jewelry",
      "Rings",
      "Necklaces & Pendants",
      "Earrings",
      "Bracelets",
      "Bangles",
      "Kadas",
      "Chains",
      "Mangalsutras",
      "Nose Pins",
      "Toe Rings",
      "Anklets",
      "Maang Tikkas",
      "Baju Bandhs",
      "Kamar Bandhs",
      "Armlets",
      "Waist Belts",
      "Brooches",
      "Cufflinks"
    ],
    "Fashion & Costume Jewelry": [
      "Oxidised Jewelry",
      "Kundan Jewelry",
      "Temple Jewelry",
      "Pearl Jewelry",
      "American Diamond (AD) Jewelry",
      "Jhumkas & Earrings",
      "Chokers & Necklaces",
      "Rings",
      "Bracelets & Cuffs",
      "Anklets & Toe Rings",
      "Hair Accessories",
      "Bangles",
      "Brooches",
      "Maang Tikkas",
      "Nose Rings",
      "Pendants",
      "Jewelry Sets",
      "Statement Jewelry",
      "Fashion Rings",
      "Fashion Bracelets",
      "Fashion Necklaces",
      "Fashion Earrings",
      "Fashion Anklets",
      "Fashion Pendants"
    ],
    "Men's Jewelry": [
      "Rings",
      "Bracelets",
      "Chains & Necklaces",
      "Pendants",
      "Earrings",
      "Kadas",
      "Cufflinks",
      "Tie Pins",
      "Money Clips",
      "Lapel Pins",
      "Studs",
      "Brooches",
      "Rings"
    ],
    "Watches": {
      "Men's Watches": [
        "Analog Watches",
        "Digital Watches",
        "Chronograph Watches",
        "Automatic Watches",
        "Smartwatches",
        "Dress Watches",
        "Casual Watches",
        "Sports Watches",
        "Diver's Watches",
        "Pilot's Watches",
        "Field Watches",
        "Solar-Powered Watches",
        "Quartz Watches"
      ],
      "Women's Watches": [
        "Analog Watches",
        "Digital Watches",
        "Fashion Watches",
        "Smartwatches",
        "Dress Watches",
        "Casual Watches",
        "Bangle Watches",
        "Bracelet Watches",
        "Necklace Watches",
        "Pocket Watches"
      ],
      "Kid's Watches": [
        "Analog Watches",
        "Digital Watches",
        "Smartwatches",
        "Character Watches",
        "Interactive Watches"
      ]
    }
  },
  "Home & Kitchen": {
    "Furniture": [
      "Living Room Furniture",
      "Bedroom Furniture",
      "Office Furniture",
      "Outdoor Furniture",
      "Dining Room Furniture",
      "Storage Furniture",
      "Accent Chairs",
      "Sofas & Sectionals",
      "Beds & Mattresses",
      "Dressers & Chests",
      "Coffee Tables",
      "Bookshelves",
      "TV Stands",
      "Desks",
      "Wardrobes",
      "Shoe Racks",
      "Kitchen Cabinets",
      "Bar Stools",
      "Benches",
      "Recliners",
      "Ottomans",
      "Side Tables",
      "Console Tables",
      "Dining Tables",
      "Dining Chairs",
      "Buffets & Sideboards",
      "Bars & Wine Racks",
      "Kitchen Islands",
      "Utility Carts",
      "Patio Furniture",
      "Hammocks",
      "Porch Swings",
      "Garden Benches",
      "Office Chairs",
      "Filing Cabinets",
      "Bookcases",
      "Lounge Chairs",
      "Chaise Lounges",
      "Stools",
      "Armoires",
      "Nightstands"
    ],
    "Kitchen & Dining": [
      "Cookware",
      "Dinnerware",
      "Glassware",
      "Kitchen Tools",
      "Cutlery",
      "Bakeware",
      "Small Appliances",
      "Food Storage",
      "Table Linens",
      "Cookware Sets",
      "Knives & Knife Blocks",
      "Cutting Boards",
      "Coffee & Tea Accessories",
      "Serving Utensils",
      "Dining Tables",
      "Dining Chairs",
      "Dinner Plates",
      "Bowls",
      "Mugs",
      "Water Bottles",
      "Frying Pans",
      "Saucepans",
      "Pressure Cookers",
      "Woks",
      "Spatulas",
      "Whisks",
      "Ladle",
      "Tongs",
      "Mixing Bowls",
      "Measuring Cups",
      "Colanders & Strainers",
      "Can Openers",
      "Bottle Openers",
      "Graters",
      "Peelers",
      "Slicers",
      "Food Scales",
      "Timers",
      "Oven Mitts",
      "Aprons",
      "Dish Racks",
      "Spice Racks",
      "Utensil Holders",
      "Paper Towel Holders",
      "Kitchen Mats",
      "Tablecloths",
      "Napkins",
      "Placemats"
    ],
    "Home Decor": [
      "Wall Decor",
      "Lamps & Lighting",
      "Clocks",
      "Cushion Covers",
      "Rugs & Carpets",
      "Curtains & Blinds",
      "Photo Frames & Albums",
      "Vases & Showpieces",
      "Candles & Holders",
      "Artificial Plants & Flowers",
      "Bedding & Linens",
      "Throws & Blankets",
      "Mirrors",
      "Home Fragrance",
      "Sculptures",
      "Wall Art",
      "Scented Candles",
      "Diffusers",
      "Ornaments",
      "Storage Baskets",
      "Pillows",
      "Duvets",
      "Blankets",
      "Bed Sheets",
      "Pillowcases",
      "Comforters",
      "Quilts",
      "Mattress Protectors",
      "Bed Skirts",
      "Headboards",
      "Wall Clocks",
      "Table Lamps",
      "Floor Lamps",
      "Ceiling Lamps",
      "Chandeliers",
      "String Lights",
      "Night Lights",
      "Wall Shelves",
      "Picture Frames",
      "Vases",
      "Figurines",
      "Desk Organizers",
      "Bookends",
      "Door Mats",
      "Wall Stickers",
      "Wallpapers"
    ],
    "Appliances": [
      "Microwave Ovens",
      "Mixers & Blenders",
      "Water Purifiers",
      "Induction Cooktops",
      "Air Fryers",
      "Coffee Makers",
      "Food Processors",
      "Toasters",
      "Electric Kettles",
      "Juicers",
      "Rice Cookers",
      "Grills & Panini Presses",
      "Cooktops",
      "Chimneys",
      "Dishwashers",
      "Vacuum Cleaners",
      "Room Heaters",
      "Air Coolers",
      "Fans",
      "Irons",
      "Washing Machines",
      "Refrigerators",
      "Televisions",
      "Air Conditioners",
      "Home Theater Systems",
      "Soundbars",
      "Speakers",
      "Headphones",
      "Earbuds",
      "Water Heaters",
      "Geysers",
      "Air Purifiers",
      "Air Fryer Ovens",
      "Electric Grills",
      "Electric Pressure Cookers",
      "Food Dehydrators"
    ],
    "Storage & Organization": [
      "Containers & Jars",
      "Shoe Racks",
      "Bookshelves",
      "Kitchen Storage",
      "Pantry Organization",
      "Closet Organization",
      "Bathroom Storage",
      "Garage Storage",
      "Laundry Baskets",
      "Shelving Units",
      "Bins & Baskets",
      "Drawer Organizers",
      "Vacuum Storage Bags",
      "Storage Boxes",
      "Wall Hooks & Racks",
      "Hangers",
      "Carts & Trolleys",
      "Filing Cabinets",
      "Tool Organizers",
      "Toy Storage",
      "Underbed Storage",
      "Over-the-Door Organizers",
      "Cabinet Organizers",
      "Desk Organizers",
      "File Boxes",
      "Label Makers",
      "Storage Racks",
      "Storage Containers",
      "Storage Baskets",
      "Jewelry Boxes",
      "Makeup Organizers",
      "Laundry Bags",
      "Pill Organizers",
      "Travel Organizers",
      "Shoe Bags",
      "Garment Bags"
    ]
  },
  "Beauty & Personal Care": {
    "Makeup": [
      "Foundation",
      "Lipstick",
      "Eyeliner",
      "Blush",
      "Mascara",
      "Concealer",
      "Eyeshadow",
      "Lip Gloss",
      "Highlighter",
      "Bronzer",
      "Makeup Brushes",
      "Primer",
      "Setting Spray",
      "Brow Products",
      "Nail Polish",
      "Lip Liner",
      "Kohl & Kajal",
      "BB & CC Creams",
      "Makeup Removers",
      "False Eyelashes",
      "Makeup Sponges",
      "Makeup Palettes",
      "Makeup Sets",
      "Makeup Bags",
      "Makeup Organizers",
      "Makeup Mirrors",
      "Makeup Lights",
      "Contour Kits",
      "Lip Stains",
      "Lip Tints",
      "Eyeshadow Palettes",
      "Eyelash Glue",
      "Eyebrow Pencils",
      "Eyebrow Gels",
      "Mascara Primers",
      "Setting Powder"
    ],
    "Skincare": [
      "Face Wash",
      "Moisturizers",
      "Sunscreen",
      "Face Masks",
      "Serums",
      "Toners",
      "Cleansers",
      "Exfoliators",
      "Acne Treatments",
      "Eye Creams",
      "Lip Balms",
      "Sheet Masks",
      "Night Creams",
      "Day Creams",
      "Facial Tools",
      "Face Oils",
      "Face Mists",
      "Facial Cleansing Devices",
      "Anti-Aging Products",
      "Skin Brightening Products",
      "Facial Scrubs",
      "Facial Moisturizers",
      "Facial Serums",
      "Facial Toners",
      "Facial Cleansers",
      "Facial Exfoliators",
      "Facial Masks",
      "Facial Oils",
      "Facial Peels",
      "Spot Treatments",
      "Pore Strips",
      "Micellar Water",
      "Cleansing Balms",
      "Eye Serums",
      "Neck Creams",
      "Body Lotions",
      "Body Scrubs",
      "Hand Creams",
      "Foot Creams",
      "Sunblock",
      "After-Sun Care"
    ],
    "Haircare": [
      "Shampoo",
      "Conditioner",
      "Hair Oil",
      "Hair Gel",
      "Hair Masks",
      "Hair Serum",
      "Hair Spray",
      "Hair Styling Tools",
      "Hair Dryers",
      "Hair Straighteners",
      "Curling Irons",
      "Hair Color",
      "Dandruff Treatment",
      "Hair Brushes & Combs",
      "Hair Accessories",
      "Hair Clips & Bands",
      "Hair Loss Treatments",
      "Dry Shampoo",
      "Volumizing Products",
      "Leave-In Conditioner",
      "Hair Treatments",
      "Hair Tonics",
      "Hair Creams",
      "Hair Mousses",
      "Hair Waxes",
      "Hair Clay",
      "Hair Pomades",
      "Hair Pastes",
      "Hair Clippers",
      "Hair Curlers",
      "Hair Rollers",
      "Hair Extensions",
      "Wigs",
      "Shampoo Bars",
      "Conditioner Bars",
      "Scalp Scrubs",
      "Hair Detox",
      "Heat Protectant Sprays",
      "UV Protectant Sprays"
    ],
    "Men's Grooming": [
      "Shaving Cream",
      "Aftershave",
      "Trimmers",
      "Face Wash",
      "Razors",
      "Shaving Gels & Foams",
      "Beard Oil & Balm",
      "Moustaches Wax",
      "Body Wash",
      "Deodorants & Perfumes",
      "Hair Styling Products",
      "Face Moisturizers",
      "Sunscreen",
      "Grooming Kits",
      "Electric Shavers",
      "Manual Razors",
      "Shaving Brushes",
      "Colognes",
      "Eye Cream",
      "Lip Balm",
      "Aftershave Balm",
      "Aftershave Lotion",
      "Beard Trimmers",
      "Body Trimmers",
      "Nose & Ear Trimmers",
      "Shaving Soap",
      "Shaving Bowls",
      "Shaving Brushes",
      "Beard Combs",
      "Beard Shampoos",
      "Beard Conditioners",
      "Beard Dyes"
    ],
    "Bath & Body": [
      "Soaps",
      "Body Wash",
      "Lotions",
      "Body Scrub",
      "Bath Bombs",
      "Body Oils",
      "Hand Wash",
      "Hand Sanitizers",
      "Hand & Foot Creams",
      "Talcum Powder",
      "Deodorants",
      "Fragrances & Perfumes",
      "Bath Salts",
      "Bath Gels",
      "Shower Gels",
      "Bubble Bath",
      "Body Sprays",
      "Solid Soaps",
      "Liquid Soaps",
      "Loofahs & Sponges",
      "Hand Creams",
      "Foot Creams",
      "Body Lotions",
      "Body Butters",
      "Body Mists",
      "Body Powders",
      "Bath & Shower Gels",
      "Bath & Shower Oils",
      "Bath Fizzies",
      "Body Polishes",
      "Body Clay Masks",
      "Hand Masks",
      "Foot Masks",
      "Feminine Hygiene Products"
    ],
    "Health & Wellness": [
      "Supplements",
      "Vitamins",
      "Health Drinks",
      "Protein Powders",
      "Weight Management",
      "Immunity Boosters",
      "Herbal Products",
      "Ayurvedic Products",
      "Nutritional Bars",
      "Health Juices",
      "Personal Care",
      "First Aid Supplies",
      "Oral Care",
      "Feminine Hygiene",
      "Sexual Wellness",
      "Sleep Aids",
      "Pain Relievers",
      "Digestive Health",
      "Bone & Joint Health",
      "Heart Health",
      "Respiratory Health",
      "Eye Health",
      "Brain Health",
      "Hair, Skin & Nails",
      "Weight Loss Supplements",
      "Muscle Growth Supplements",
      "Energy Supplements",
      "Immunity Supplements",
      "Dietary Supplements",
      "Herbal Teas",
      "Nut Butters",
      "Probiotics",
      "Prebiotics",
      "Medical Devices",
      "Homeopathic Products",
      "Aromatherapy",
      "Essential Oils"
    ],
    "Beauty Tools & Equipment": [
      "Makeup Brushes & Sponges",
      "Hair Dryers",
      "Hair Straighteners & Curlers",
      "Facial Cleansing Devices",
      "Massagers & Gua Sha",
      "Electric Shavers & Trimmers",
      "Manicure & Pedicure Kits",
      "Eyelash Curlers",
      "Hair Clippers",
      "Nail Care Tools",
      "Waxing & Hair Removal Devices",
      "Storage & Organizers",
      "Electric Toothbrushes",
      "Water Flossers",
      "Foot Massagers",
      "Facial Steamers",
      "Facial Rollers",
      "Microdermabrasion Machines"
    ]
  },
  "Grocery & Staples": {
    "Fresh Produce": [
      "Fruits",
      "Vegetables",
      "Leafy Greens",
      "Herbs & Spices",
      "Organic Produce",
      "Exotic Fruits",
      "Exotic Vegetables",
      "Seasonal Fruits",
      "Seasonal Vegetables",
      "Juicing Fruits",
      "Salad Vegetables",
      "Cooking Herbs",
      "Fresh Spices",
      "Root Vegetables",
      "Berries",
      "Melons",
      "Citrus Fruits",
      "Potatoes & Onions",
      "Tomatoes & Peppers",
      "Cabbages & Cauliflowers",
      "Mushrooms",
      "Cucumbers",
      "Beans",
      "Peas",
      "Corn",
      "Garlic",
      "Ginger",
      "Chillies",
      "Lemons",
      "Limes",
      "Carrots",
      "Broccoli",
      "Spinach",
      "Cilantro",
      "Parsley",
      "Basil",
      "Apples",
      "Bananas",
      "Oranges",
      "Grapes"
    ],
    "Dairy & Eggs": [
      "Milk",
      "Cheese",
      "Yogurt",
      "Eggs",
      "Butter & Ghee",
      "Cream & Sour Cream",
      "Paneer & Tofu",
      "Dairy Alternatives",
      "Flavored Milk",
      "Lassi & Buttermilk",
      "Curd",
      "Cottage Cheese",
      "Processed Cheese",
      "Cheddar Cheese",
      "Mozzarella Cheese",
      "Greek Yogurt",
      "Probiotic Yogurt",
      "Organic Milk",
      "Free-Range Eggs",
      "Pasteurized Milk",
      "Skimmed Milk",
      "Full Cream Milk",
      "Low Fat Milk",
      "Lactose Free Milk",
      "Almond Milk",
      "Soy Milk",
      "Oat Milk",
      "Coconut Milk",
      "Condensed Milk",
      "Evaporated Milk",
      "Goat Milk",
      "Sheep Milk",
      "Buffalo Milk",
      "Organic Eggs",
      "Brown Eggs",
      "White Eggs",
      "Duck Eggs",
      "Quail Eggs"
    ],
    "Staples & Pulses": [
      "Rice",
      "Flour",
      "Dals & Pulses",
      "Spices",
      "Oils",
      "Sugar & Jaggery",
      "Salt",
      "Dry Fruits & Nuts",
      "Pasta & Noodles",
      "Cereals & Grains",
      "Cooking Pastes",
      "Pickles & Chutneys",
      "Papad & Chips",
      "Indian Breads & Rotis",
      "Ready-to-Eat Meals",
      "Breakfast Mixes",
      "Honey & Syrups",
      "Vinegar & Sauces",
      "Baking Supplies",
      "Condiments",
      "Basmati Rice",
      "Jasmine Rice",
      "Brown Rice",
      "White Rice",
      "Atta Flour",
      "Maida Flour",
      "Gram Flour",
      "Rice Flour",
      "Corn Flour",
      "Toor Dal",
      "Moong Dal",
      "Urad Dal",
      "Masoor Dal",
      "Chana Dal",
      "Rajma",
      "Kabuli Chana",
      "Black-eyed Peas",
      "Lentils",
      "Quinoa",
      "Oats",
      "Barley",
      "Millet",
      "Spaghetti",
      "Macaroni",
      "Penne",
      "Couscous"
    ],
    "Snacks & Packaged Food": [
      "Biscuits",
      "Chocolates",
      "Chips",
      "Noodles",
      "Cereals",
      "Cookies",
      "Crackers",
      "Snack Bars",
      "Energy Bars",
      "Popcorn",
      "Namkeen & Savories",
      "Wafers",
      "Candies & Gums",
      "Jams & Spreads",
      "Ready-to-Cook Mixes",
      "Soups",
      "Frozen Foods",
      "Ice Cream",
      "Canned Foods",
      "Jellies & Puddings",
      "Breakfast Cereals",
      "Instant Noodles",
      "Pasta",
      "Packaged Snacks",
      "Packaged Sweets",
      "Packaged Savouries",
      "Packaged Chocolates",
      "Packaged Biscuits",
      "Packaged Crackers",
      "Granola",
      "Muesli",
      "Dried Fruits",
      "Nuts",
      "Seeds",
      "Fruit Rolls",
      "Trail Mixes",
      "Pretzels",
      "Jerky",
      "Fruit Cups"
    ],
    "Beverages": [
      "Soft Drinks",
      "Juices",
      "Coffee",
      "Tea",
      "Water Bottles",
      "Energy Drinks",
      "Health Drinks",
      "Sports Drinks",
      "Juice Concentrates",
      "Flavored Syrups",
      "Hot Chocolate Mixes",
      "Green Tea",
      "Herbal Tea",
      "Instant Coffee",
      "Filter Coffee",
      "Loose Leaf Tea",
      "Soda",
      "Iced Tea Mix",
      "Ready-to-Drink Coffee",
      "Milk Shakes & Smoothies",
      "Protein Drinks",
      "Vitamin Water",
      "Flavored Water",
      "Coconut Water",
      "Fruit Juices",
      "Vegetable Juices",
      "Smoothie Mixes",
      "Coffee Pods",
      "Sparkling Water",
      "Tonic Water",
      "Kombucha",
      "Kefir",
      "Electrolyte Drinks",
      "Drink Mixes",
      "Powdered Juices",
      "Energy Shots",
      "Smoothie Bowls",
      "Protein Shakes",
      "Meal Replacement Shakes"
    ]
  },
  "Books & Media": {
    "Fiction": [
      "Classic",
      "Thriller",
      "Fantasy",
      "Romance",
      "Science Fiction",
      "Horror",
      "Mystery",
      "Literary Fiction",
      "Young Adult Fiction",
      "Historical Fiction",
      "Crime & Detective",
      "Graphic Novels",
      "Short Story Collections",
      "Poetry",
      "Dystopian Fiction",
      "Contemporary Fiction",
      "Satire",
      "Gothic Fiction",
      "Speculative Fiction",
      "Fables & Fairy Tales",
      "Adventure Fiction",
      "Action & Adventure",
      "Coming of Age",
      "Humor",
      "Magical Realism",
      "Mythology & Folklore",
      "Paranormal & Urban Fantasy",
      "Steampunk",
      "Westerns",
      "Epic Fantasy",
      "Children's Fiction",
      "Teen & Young Adult",
      "New Adult",
      "Middle Grade",
      "Cozy Mystery",
      "Hardboiled Detective",
      "Spy Thriller",
      "Psychological Thriller",
      "Political Thriller",
      "Legal Thriller",
      "Medical Thriller",
      "Techno-Thriller",
      "Space Opera",
      "Cyberpunk",
      "Military Science Fiction"
    ],
    "Non-Fiction": [
      "Biography",
      "Self-Help",
      "History",
      "Science",
      "Cookbooks",
      "Travel Guides",
      "Business & Finance",
      "Health & Wellness",
      "Politics",
      "Philosophy",
      "Religion & Spirituality",
      "Art & Photography",
      "Psychology",
      "True Crime",
      "Essays",
      "Memoirs",
      "Academic & Educational",
      "Nature & Environment",
      "Technology",
      "Pop Culture",
      "Parenting & Families",
      "Crafts, Hobbies & Home",
      "Computers & Technology",
      "Sports & Outdoors",
      "Law & Crime",
      "Food & Drink",
      "Medical",
      "Social Sciences",
      "Reference",
      "Foreign Language Study",
      "Autobiography",
      "Personal Finance",
      "Investing",
      "Marketing",
      "Management",
      "Leadership",
      "Microeconomics",
      "Macroeconomics",
      "Physics",
      "Chemistry",
      "Biology",
      "Astronomy",
      "Geology",
      "Sociology",
      "Anthropology",
      "Archaeology",
      "World History",
      "US History"
    ],
    "Children's Books": [
      "Storybooks",
      "Activity Books",
      "Picture Books",
      "Board Books",
      "Early Readers",
      "Chapter Books",
      "Young Adult",
      "Non-Fiction for Kids",
      "Coloring Books",
      "Puzzle Books",
      "Pop-Up Books",
      "Interactive Books",
      "Sticker Books",
      "Sound Books",
      "Rhyming Books",
      "Books for Toddlers",
      "Books for Pre-Teens",
      "Educational Books",
      "Dictionaries",
      "Atlases",
      "Children's Classics",
      "Children's Picture Books",
      "Children's Chapter Books",
      "Children's Board Books",
      "Children's Activity Books",
      "Children's Coloring Books",
      "Children's Puzzle Books",
      "Children's Sticker Books",
      "Children's Sound Books",
      "Poetry for Kids",
      "Fairy Tales",
      "Fantasy for Kids",
      "Science Fiction for Kids",
      "Adventure for Kids",
      "Graphic Novels for Kids",
      "DIY Books for Kids",
      "Jokes for Kids"
    ],
    "E-books & Audiobooks": [
      "E-books",
      "Audiobooks",
      "Magazines",
      "Newspapers",
      "Comic Books",
      "Digital Textbooks",
      "Podcasts",
      "Digital Comics",
      "E-Readers",
      "Audio Players",
      "Digital Journals",
      "Digital Cookbooks",
      "E-book Subscriptions",
      "Audiobook Subscriptions",
      "Digital Music Albums",
      "Digital Movies & TV Shows",
      "Gaming Subscriptions",
      "Digital Photo Albums",
      "Digital Art Collections",
      "Digital Catalogs",
      "Kindle Books",
      "Nook Books",
      "Apple Books",
      "Google Play Books",
      "Audible Audiobooks",
      "Scribd Audiobooks",
      "Storytel Audiobooks",
      "LibriVox Audiobooks",
      "eBook Readers",
      "eBook Tablet",
      "eBook Software"
    ]
  },
  "Sports & Fitness": {
    "Outdoor Sports": [
      "Cricket",
      "Football",
      "Badminton",
      "Tennis",
      "Basketball",
      "Soccer",
      "Baseball",
      "Golf",
      "Hockey",
      "Volleyball",
      "Running",
      "Cycling",
      "Skateboarding",
      "Rollerblading",
      "Swimming",
      "Water Sports",
      "Snow Sports",
      "Camping & Hiking",
      "Fishing",
      "Archery",
      "Hunting",
      "Equestrian",
      "Climbing",
      "Kayaking",
      "Canoeing",
      "Sailing",
      "Surfing",
      "Wakeboarding",
      "Waterskiing",
      "Lacrosse",
      "Rugby",
      "Fencing",
      "Martial Arts",
      "Boxing",
      "Wrestling",
      "Gymnastics",
      "Track & Field"
    ],
    "Fitness & Gym": [
      "Yoga Mats",
      "Dumbbells",
      "Exercise Bikes",
      "Treadmills",
      "Workout Benches",
      "Weight Plates",
      "Resistance Bands",
      "Kettlebells",
      "Exercise Balls",
      "Skipping Ropes",
      "Gym Gloves",
      "Fitness Apparel",
      "Protein Powders",
      "Supplements",
      "Shakers & Bottles",
      "Smart Scales",
      "Foam Rollers",
      "Jump Ropes",
      "Ab Rollers",
      "Pull-Up Bars",
      "Barbells",
      "Weight Benches",
      "Squat Racks",
      "Power Racks",
      "Medicine Balls",
      "Battle Ropes",
      "Kettlebell Sets",
      "Dumbbell Racks",
      "Weight Vests",
      "Elliptical Machines",
      "Rowing Machines",
      "Stair Climbers",
      "Fitness Trackers",
      "Heart Rate Monitors",
      "Workout DVDs",
      "Workout Apps"
    ],
    "Outdoor Adventures": [
      "Camping Gear",
      "Hiking Equipment",
      "Trekking Poles",
      "Tents",
      "Sleeping Bags",
      "Backpacks",
      "Camping Stoves",
      "Headlamps & Flashlights",
      "Water Filters",
      "First Aid Kits",
      "Camping Furniture",
      "Coolers",
      "Hiking Boots",
      "Climbing Gear",
      "Ropes & Carabiners",
      "Navigation Tools",
      "Outdoor Apparel",
      "Snowshoes",
      "Skis & Snowboards",
      "Kayaks & Canoes",
      "Paddleboards",
      "Fishing Gear",
      "Hunting Gear",
      "Survival Kits",
      "Binoculars",
      "Telescopes",
      "Outdoor Power Equipment",
      "Outdoor Cooking",
      "Outdoor Lighting",
      "Sleeping Pads",
      "Camp Chairs",
      "Hammocks",
      "Fire Starters",
      "Bear Spray",
      "Maps & Compasses",
      "GPS Devices",
      "Insect Repellent",
      "Sunscreen"
    ],
    "Indoor Games": [
      "Board Games",
      "Carrom",
      "Chess",
      "Table Tennis",
      "Billiards & Pool Tables",
      "Foosball Tables",
      "Air Hockey Tables",
      "Dartboards",
      "Puzzles",
      "Card Games",
      "Dice Games",
      "Video Game Consoles",
      "PC Games",
      "Party Games",
      "Strategy Games",
      "Role-Playing Games",
      "Jigsaw Puzzles",
      "Dominoes",
      "Checkers",
      "Mahjong",
      "Backgammon",
      "Poker Sets",
      "Roulette Sets",
      "Blackjack Sets",
      "Cribbage Boards",
      "Domino Sets",
      "Checkers Sets",
      "Mahjong Sets",
      "Ludo",
      "Snakes and Ladders",
      "Monopoly",
      "Scrabble",
      "Clue",
      "Ticket to Ride",
      "Catan"
    ]
  },
  "Hotels & Stays": {
    "Hotel Types": [
      "Business Hotels",
      "Boutique Hotels",
      "Luxury Hotels",
      "Resorts",
      "Budget Hotels",
      "Hostels",
      "Homestays",
      "Vacation Rentals",
      "Apartment Hotels",
      "Guesthouses",
      "Bed & Breakfasts",
      "Eco-Lodges",
      "Spa & Wellness Retreats",
      "All-Inclusive Resorts",
      "Pet-Friendly Stays",
      "Family Hotels",
      "Adult-Only Resorts",
      "Casino Hotels",
      "Beachfront Hotels",
      "Ski Resorts",
      "City Hotels",
      "Country Hotels",
      "Airport Hotels",
      "Conference Hotels",
      "Convention Hotels",
      "Resort Hotels",
      "Spa Hotels",
      "Boutique Resorts",
      "Extended Stay Hotels",
      "Motels",
      "Capsule Hotels",
      "Farm Stays",
      "Treehouse Resorts",
      "Floating Hotels",
      "Ice Hotels",
      "Glamping Sites"
    ],
    "By Location": [
      "Domestic",
      "International",
      "Urban Stays",
      "Rural Stays",
      "Coastal Stays",
      "Mountain Stays",
      "Island Stays",
      "Desert Stays",
      "City Center",
      "Near Airport",
      "Near Train Station",
      "Near Tourist Attractions",
      "Off-the-Beaten-Path Stays",
      "Eco-Tourism Destinations",
      "Safari Lodges",
      "Historical Locations",
      "Downtown Stays",
      "Suburban Stays",
      "Secluded Retreats",
      "Lakefront Properties",
      "Riverfront Properties",
      "Oceanfront Properties",
      "Forest Properties",
      "Jungle Properties",
      "Beach Properties",
      "Mountain Properties",
      "Desert Properties",
      "Island Properties",
      "Ski-In/Ski-Out Stays",
      "Vineyard Stays",
      "Ranch Stays",
      "Farm Stays",
      "City Break Hotels"
    ],
    "Amenities": [
      "Swimming Pool",
      "Spa & Wellness",
      "Restaurant",
      "Conference Rooms",
      "Free Wi-Fi",
      "Parking",
      "Gym & Fitness Center",
      "Pet-Friendly",
      "Breakfast Included",
      "Room Service",
      "Laundry Service",
      "Shuttle Service",
      "Childcare Services",
      "Bar & Lounge",
      "Business Center",
      "Concierge Service",
      "Wheelchair Accessible",
      "In-Room Safe",
      "Kitchenette",
      "Private Balcony",
      "Terrace",
      "Garden",
      "Patio",
      "Private Pool",
      "Hot Tub",
      "Sauna",
      "Steam Room",
      "Jacuzzi",
      "Minibar",
      "Coffee Maker",
      "Hair Dryer",
      "Ironing Board",
      "Desk",
      "Fireplace",
      "Game Room",
      "Library",
      "Gift Shop",
      "Tennis Court",
      "Golf Course",
      "Cinema"
    ],
    "Room Types": [
      "Single",
      "Double",
      "Suite",
      "Family Room",
      "Standard Room",
      "Deluxe Room",
      "Executive Room",
      "Studio",
      "Connecting Rooms",
      "Accessible Rooms",
      "Smoking Rooms",
      "Non-Smoking Rooms",
      "Ocean View Rooms",
      "Mountain View Rooms",
      "City View Rooms",
      "Garden View Rooms",
      "Dormitories",
      "Private Cottages",
      "Villas",
      "Cabins",
      "Lofts",
      "Penthouses",
      "Bungalows",
      "Condos",
      "Apartments",
      "Townhouses",
      "Junior Suites",
      "Presidential Suites",
      "Honeymoon Suites",
      "Cottages",
      "Treehouses",
      "Tents"
    ],
    "Booking Duration": [
      "Short-Term Stays",
      "Extended Stays",
      "Weekly",
      "Monthly",
      "Hourly Stays",
      "Day Use",
      "Overnight Stays",
      "Weekend Getaways",
      "Holiday Packages",
      "Business Trip Stays",
      "Long-Term Rentals",
      "Corporate Housing",
      "Event Bookings",
      "Wedding Stays",
      "Group Bookings",
      "Student Housing",
      "Medical Stays",
      "Emergency Bookings",
      "Last-Minute Bookings",
      "Advance Reservations",
      "Half Day Stays",
      "Full Day Stays",
      "Single Night Stays",
      "Multi Night Stays",
      "Workation Packages",
      "Staycations",
      "Vacation Packages"
    ]
  }
}; 